### ISSUE TITLE
After signout as super user, the next created user will become a sub-user to the super-user

### ISSUE THREAD

**Issue by mapcentia** [sashuk/dashboard#12]
1. Sign in with a super user.
2. Sign out agian.
3. Registre a new user

The new user is now a sub-user to the super-user (1).
The new user was expected to become a super user.

**Comment by sashuk** [comment]
@mapcentia Could you please specify the browser or URL where this was observed? Seems like the PHP session cookie is not destroyed on the sign out.

![users](https://user-images.githubusercontent.com/1390758/58556819-7c3e5d80-824f-11e9-9bd3-daa62aad5ba8.gif)

**Comment by mapcentia** [comment]
@sashuk Chrome on local develop machine

**Comment by sashuk** [comment]
@mapcentia The case was recreated:
- sign out from super-user account;
- turn off the backend;
- refresh the page and receive a redirect to the sign-in page (during this step the `PHPSESSID` cookie is now destroyed);
- register new user

Fixed in https://github.com/sashuk/dashboard/commit/8c143f8183f6d6cb1d38bd1afe46ff236e37bc3a
